### ISSUE TITLE
feature: Update to latest stable Spring Boot version

### ISSUE THREAD

**Issue by mariorguezari** [AriHealth/spring-boot-template#12]
# Feature Request

**Describe the Feature Request**

There is a 2.3.X version, newer than 2.2.X that is used in the template.

**Describe Preferred Solution**

Use the 2.3.X version listed here in pom: 
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot

**Comment by carloscaverobarca** [comment]
Yes this should be upgraded accordingly. As you can see it includes code coverage, unit testing with Mockito. It is what I use when I configure a new Spring project. Please send a PR if you can.
